on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - ffmpeg-build-released
      - qbittorrent-custom-built
  push:
    branches:
      - master
    paths:
      - 'bucket/*.json'
      - 'scripts/**/*.reg'
  schedule:
    # run every 30 minutes
    - cron: '13 * * * *'
name: Excavator
permissions:
  contents: write
jobs:
  excavate:
    name: Excavate
    if: github.event_name != 'push' || github.actor != 'github-actions[bot]'
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
