on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - ffmpeg-build-released
  push:
    branches:
      - master
    paths:
      - 'bucket/*.json'
      - 'scripts/**/*.reg'
  schedule:
    # run every 30 minutes
    - cron: '13 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
