on:
  issue_comment:
    types: [created]
name: Commented Pull Request
permissions:
  actions: read
  contents: read
  pull-requests: write
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # main 2026-08-21
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
